VITE:
  server:
    port: 3000
    host: true
OPENAPI_SCHEMA_PATH: ../openapi_schema.json
UNKNOWN_COLOR: 'd5d5d5'
DEFAULT_N_GAMES_PER_ROUND: 6
DEFAULT_N_ROUNDS: 8
DEFAULT_N_DIVISIONS: 2
DEFAULT_N_TEAMS_PER_DIVISION: 6
DEFAULT_N_DIVISIONS_PER_GAME: 1
